### PR TITLE
fix(preview): slightly defer skipping header for correct preview

### LINKED ISSUE #42: Preview windows show wrong position of file
### Description

Preview windows display wrong position of some files when first select them, and preview window display correctly when selecting it for the second time

https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/54128430/fef3750d-796b-471d-835c-be26d9c4dcdc

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Windows 11

### Steps to reproduce

1. `nvim`
2. `<space>/`
3. `init = `
4. `<c-n>`

### Expected behavior

Preview window should display the matched line

### Actual behavior

Preview window should display top of some files when first select them.

### Minimal config

```Lua
-- init.lua
-- Bootstrap plugins manager
local lazy_path = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazy_path) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--branch=stable",
    "https://github.com/folke/lazy.nvim.git",
    lazy_path,
  })
end
vim.opt.rtp:prepend(lazy_path)

-- Load user configs before load plugins
require("user.configs")
-- vim.g.mapleader = " "

require("lazy").setup({
  -- Load plugin specifics in directories
  spec = {
    { import = "user/plugins" },
    { import = "user/langs" },
    -- { import = "user/test" },
  },
  install = {
    -- Try to load one of these colorschemes when starting an installation during startup
    colorscheme = { "tokyonight", "catppuccin", "habamax" },
  },
  change_detection = {
    -- Do not automatically check for config file changes and reload the ui
    enabled = false,
  },
  performance = {
    rtp = {
      disabled_plugins = {
        "gzip",
        "matchit",
        "matchparen",
        "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})

-- lua/user/test/egrepify.lua
return {
  {
    "nvim-telescope/telescope.nvim",
    opts = {},
  },
  -- Better live_grep that could change rg arguments on fly
  {
    "fdschmidt93/telescope-egrepify.nvim",
    keys = {
      { "<Leader>/", "<Cmd>Telescope egrepify<CR>", desc = "Search Text" },
    },
    config = function()
      require("telescope").load_extension("egrepify")
    end,
  },
}
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Fix #42

@mrbeardad could you please confirm this fixes your issue? :)

### CODE REVIEW

**Comment by mrbeardad** [comment]
@fdschmidt93 It is improved, but still exist.

**Comment by megalithic** [comment]
Initial usage of this branch looks to fix it for me (again, initial usage, will continue with this branch through out the day and report back). thanks for filing this @mrbeardad and thanks for the plugin and fixes, @fdschmidt93!

**Comment by mrbeardad** [comment]
It works good in mini init.lua, but not after install lots of plugins that make my nvim slow.

**Comment by fdschmidt93** [comment]
I'm afraid this is a mega stupid bug. The solution now is also quite hacky, but anything else didn't seem to always work or would be significantly more complicated.

Please confirm this resolves this issue fully on your end :)

**Comment by mrbeardad** [comment]
@fdschmidt93 I'm sorry for the late reply. The issue about the wrong preview position is gone, but there is another bug that does not appear in master, to reproduce it:
1. type `<space>/` to open egrepify
2. type `a` to search something
3. type `<c-p>` to select previous item
4. ui freezed until type `<c-c>` to interrupt (expect to select the last item)

**Comment by fdschmidt93** [comment]
Thanks for reporting! Haven't tried reproducing but can very well imagine that this happens.

I'm afraid I most likely will only be able to be getting back to this some time in August. My apologies.

**Comment by mrbeardad** [comment]
Thanks for your working on this :)

**Comment by evkorotkov** [comment]
@fdschmidt93 @mrbeardad 
I fixed this problem in a slightly different way for myself
could you take a look, does it make sense.. https://github.com/fdschmidt93/telescope-egrepify.nvim/pull/48

**Comment by fdschmidt93** [comment]
Closing this as superseded by #48 

Thank you @evkorotkov!

**Pull request closed without merging**
