### PR TITLE
fix: enable to open files with supplied cwd

### PR DESCRIPTION
**Pull request by delphinus**
I noticed I cannot open files with `cwd=/path/to/foo/dir` option.

```bash
# Run Neovim in my home directory
~ $ nvim
```

```vim
" And open egrepify with specifying cwd
:Telescope egrepify cwd=/path/to/foo/dir
```

Then I select `bar/init.lua`, it tries to open `~/bar/init.lua` instead of `/path/to/foo/dir/bar/init.lua`.

I fixed this with joining `cwd` value and relative path in `filename`. Is this a correct way to solve this? How do you think?

### CODE REVIEW

**Review by fdschmidt93 — COMMENTED** [review]
Ah, the issues I never ran into with options I don't use myself :sweat_smile:

> I fixed this with joining cwd value and relative path in filename. Is this a correct way to solve this? How do you think?

Yeah, that is what upstream telescope is doing. I'd be mostly concerned with a slight performance hit here, since unlike upstream we create `plenary.Path` here eagerly.

`vim.fs` and `Path:new(cwd, rel_path).filename` require 2us each though benchmarks are quite flaky. So it's probably fine I guess. Lazy evaluation would reduce cost by roughly ~4x. String concatenation (we should get away with but requires maybe more precautions like setting --path-separator in `rg` to `require "plenary.path".path.sep`) would reduce this another ~2x.

```lua
local bench = require "plenary.benchmark"
local Path = require "plenary.path"
local filename = "doc/telescope-egrepify.txt"
local cwd = vim.loop.cwd()
local os_sep = Path.path.sep

vim.print(Path:new(cwd, filename):absolute())
vim.print(Path:new(cwd .. "/", filename).filename)
vim.print(vim.fs.joinpath(cwd, filename))

bench("plenary vs vim fs", {
  warmup = 20,
  runs = 500,
  fun = {
    {
      "plenary absolute",
      function()
        return Path:new(cwd, filename):absolute()
      end,
    },
    {
      "plenary filename",
      function()
        return Path:new(cwd, filename).filename
      end,
    },
    {
      "vim.fs",
      function()
        return vim.fs.joinpath(cwd, filename)
      end,
    },
    {
      "lazy",
      function()
        setmetatable({}, {
          __index = function(self, k)
            if k == "path" then
              return Path:new(cwd, filename).filename
            end
          end,
        })
      end,
    },
    {
      "concat'd",
      function()
        return cwd .. os_sep .. filename
      end,
    },
  },
})
```

Thoughts? In case of 10s of thousands of matches this accumulates a bit I guess, but not sure if this has an impact in practice. Happy to merge as is.

Thanks :)

E: this got a bit out of hand :laughing:

**Comment by delphinus** [comment]
I agree. `Path:new()` is too much way for joining paths, for sure.

BTW, `vim.fs.joinpath` has two problems. First, it naively uses `/` for path, so fails in Windows (maybe). Second, this func is unavailable v0.9.x that telescope.nvim still supports.

I will rewrite by using `cwd .. Path.path.sep .. filename`.

**Comment by fdschmidt93** [comment]
> Second, this func is unavailable v0.9.x that telescope.nvim still supports.

Great point! Makes the decision easy :)

> BTW, vim.fs.joinpath has two problems. First, it naively uses / for path, so fails in Windows (maybe).

Oof. Windows does also support forward slashes generally speaking, but we would have had to jump through more hoops (i.e., setting forward slash in `--path-separator` explicitly).

**Comment by fdschmidt93** [comment]
Thanks!

Just incorporated a fix (using `entry.path` since `filename` otherwise clashes with entry maker when `actions.to_fuzzy_refine` is called) and also as a precaution added it to title.

**Pull request merged**
